FCCBulkyBookWeb/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FCCBulkyBookWeb.Models;

public class Category
{
    [Key]
    public int Id { get; set; }
    [Required]
    public string Name { get; set; }
    [DisplayName("Display Order")]
    [Range(1,100,ErrorMessage = "Display Order must be between 1 and 100 only!! ")]
    public int DisplayOrder { get; set; }
    public DateTime CreatedDateTime { get; set; } = DateTime.Now;
}

FCCBulkyBookWeb/Models/ErrorViewModel.cs
namespace FCCBulkyBookWeb.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

FCCBulkyBookWeb/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FCCBulkyBookWeb.Data;
using FCCBulkyBookWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace FCCBulkyBookWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _context.Categories;
            return View(objCategoryList);
        }

        // GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
            }

            if (ModelState.IsValid)
            {
                _context.Categories.Add(category);
                _context.SaveChanges();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET
        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = _context.Categories.FirstOrDefault(c => c.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
            }

            if (ModelState.IsValid)
            {
                _context.Categories.Update(category);
                _context.SaveChanges();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = _context.Categories.FirstOrDefault(c => c.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var category = _context.Categories.FirstOrDefault(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            _context.Categories.Remove(category);
            _context.SaveChanges();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");


            return View();
        }
    }
}

FCCBulkyBookWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FCCBulkyBookWeb.Models;

namespace FCCBulkyBookWeb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FCCBulkyBookWeb/Views/Category/Create.cshtml
@model Category

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Category</h2>
            <hr/>
        </div>
        @* <div asp-validation-summary="All"></div> *@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control"/>
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width: 150px">Back to List</a>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

FCCBulkyBookWeb/Views/Category/Delete.cshtml
@model Category

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Category</h2>
            <hr/>
        </div>
        @* <div asp-validation-summary="All"></div> *@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" disabled class="form-control"/>

        </div>
        <button type="submit" class="btn btn-danger" style="width: 150px">Delete </button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width: 150px">Back to List</a>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

FCCBulkyBookWeb/Views/Category/Edit.cshtml
@model Category

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Category</h2>
            <hr/>
        </div>
        @* <div asp-validation-summary="All"></div> *@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control"/>
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-primary" style="width: 150px">Update </button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width: 150px">Back to List</a>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

FCCBulkyBookWeb/Views/Category/Index.cshtml
@model IEnumerable<Category>

@{
    ViewBag.Title = "Category";
    Layout = "_Layout";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col -6">
            <h2 class="text-primary">Category List</h2>
        </div>
        <div class="col -6 text-end">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>&nbsp; Create
            </a>
        </div>
    </div>


    <table class="table table-bordered table-striped col-12">
        <thead>
        <tr>
            <th>Category Name</th>
            <th>Display Order</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td class="col-6">
                    @obj.Name
                </td>
                <td class="col-3">
                    @obj.DisplayOrder
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Category" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary">
                            <i class="bi bi-pencil-square"></i> Edit
                        </a>
                        <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.Id"
                                                   class="btn btn-danger">
                                                    <i class="bi bi-trash-fill"></i> Delete
                                                </a>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

FCCBulkyBookWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FCCBulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FCCBulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/bootswatch.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/FCCBulkyBookWeb.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">
                            Home
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                    </li>

                    @* <li class="nav-item dropdown"> *@
                    @*   <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a> *@
                    @*   <div class="dropdown-menu"> *@
                    @*     <a class="dropdown-item" href="#">Action</a> *@
                    @*     <a class="dropdown-item" href="#">Another action</a> *@
                    @*     <a class="dropdown-item" href="#">Something else here</a> *@
                    @*     <div class="dropdown-divider"></div> *@
                    @*     <a class="dropdown-item" href="#">Separated link</a> *@
                    @*   </div> *@
                    @* </li> *@
                </ul>
                <form class="d-flex">
                    <input class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <partial name="_Notification"/>
        @RenderBody()
    </main>
</div>

<footer class="bg-dark footer text-muted mt-5">
    <div class="container">
        &copy; 2023 - FCCBulkyBookWeb - TungDS12- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FCCBulkyBookWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.error('@TempData["error"]')
    </script>
}